-- drop sequence if exists id_seq;
drop sequence id_seq;

create sequence id_seq
	start with 1
	increment by 1
	nocache;

drop table student_roster;
-- drop table if exists student_roster;

create table student_roster (
	--id_num int generated by default as identity primary key,
  id_num int primary key,
	student_name varchar2(25) not null,
	dateofbirth date not null
);

insert into student_roster (
	id_num,
	student_name,
	dateofbirth
	)

select id_seq.nextval, name, dob
from quiz2data
where dob is not null;

insert into student_roster (
	id_num,
	student_name,
	dateofbirth
	)
values (id_seq.nextval, 'Sarah', 07-23-2006);
