SELECT
    STUDENT.STUDENT_ID,
    STUDENT.NAME,
    STUDENT.DOB,
    STUDENT.CELL_PHONE_NUMBER,
    CLUB.CLUB_NAME,
    CLUB_MEMBERSHIP.TIME_SPENT_IN_MINUTES
FROM
    STUDENT
JOIN
    CLUB_MEMBERSHIP ON STUDENT.STUDENT_ID = CLUB_MEMBERSHIP.STUDENT_ID
JOIN
    CLUB ON CLUB_MEMBERSHIP.CLUB_ID = CLUB.CLUB_ID;
